name: Python build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Pylint
      run: |
        poetry run pylint src/ api.py --disable=C0114,C0115,C0116
    - name: isort
      run: |
        poetry run isort . --check
    - name: black
      run: |
        poetry run black . --check
